# Generated by Django 3.0.4 on 2020-03-15 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('comments', '0002_comments_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportComment',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_content', models.CharField(max_length=255)),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.Comments')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
