# Generated by Django 3.0.3 on 2020-03-21 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_reportcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reportcomment',
            name='user',
        ),
    ]
