# Generated by Django 2.0 on 2020-03-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20200312_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='current_amout',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
