# Generated by Django 2.0 on 2020-03-13 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_current_amout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('donate_id', models.AutoField(primary_key=True, serialize=False)),
                ('donate_amount', models.IntegerField()),
                ('proejct', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
        ),
    ]
