# Generated by Django 3.0.4 on 2020-03-16 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('project', '0007_report_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_charge_id', models.CharField(max_length=50)),
                ('amout', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('proejct', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.Project')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.User')),
            ],
        ),
    ]
