# Generated by Django 3.0.4 on 2020-03-16 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='proejct',
            new_name='project',
        ),
    ]
