# Generated by Django 3.0.3 on 2020-03-16 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('project', '0008_rating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('project_id', 'user_id')},
        ),
    ]
