# Generated by Django 3.0.4 on 2020-03-16 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20200316_2034'),
        ('project', '0009_auto_20200316_1607'),
    ]

    operations = [
    ]
