# Generated by Django 3.0.4 on 2020-03-18 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_donation_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='proejct',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='amout',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='proejct',
            new_name='project',
        ),
    ]
