# Generated by Django 3.0.4 on 2020-03-22 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_auto_20200321_2155'),
        ('project', '0015_auto_20200322_0857'),
    ]

    operations = [
    ]
