# Generated by Django 3.0.4 on 2020-03-22 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_merge_20200322_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount',
            new_name='payment_amount',
        ),
    ]
