# Generated by Django 3.0.3 on 2020-03-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200321_2143')
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='u_id',
            field=models.AutoField(default=10, primary_key=True, serialize=False),
            preserve_default=False,
        )
    ]
